@startuml UseCasesSearch

!include ../../_style.puml
left to right direction

title Search

actor User as user

package "Search" {
  usecase "Search\n(Songs / Albums / Playlists /\nUsers / Artists)" as UC_SEARCH
  usecase "Browse Feed" as UC_BROWSE
  usecase "Filter Feed by relation\n(mine / followed / friends)" as UC_FILTER
}

user --> UC_SEARCH
user -left-> UC_BROWSE

UC_FILTER ..> UC_BROWSE : <<extend>>

@enduml
