@startuml BackendBase

skinparam groupInheritance 2
skinparam linetype ortho
skinparam nodesep 70
skinparam ranksep 100
' INFO: all images are represented as their paths(strings)

' INFO: all models inherit from `BaseModel`,
'  not inserting actual links in order no to clutter the diagram
class BaseModel<<DjangoModel>>{
    ' uuidv7
    + uuid: UUID
    + date_created: datetime
    + date_modified: datetime
}

' ### Users
class BaseUser<<DjangoModel>>{
    ' unique
    + login: str
    + email: str

    + first_name: str
    + last_name: str
    + display_name: str
    + avatar: str | None

    + is_admin: bool
    ' auth stuff later
}

class StreamingUser<<DjangoModel>>{
    + song_queue: LinkedList[BaseSong]
'    + spaceTaken: int - future
}
StreamingUser "1"*--->"1" SongCollection: liked_songs
StreamingUser "0..* \n followed_song_collections" <---> "0..* \n followers" SongCollection
StreamingUser "0..* \n created_song_collections" <---> "0..* \n created_by" SongCollection
StreamingUser "1 \n stream_history" *---> "0..* \n user" Stream
BaseUser <|- StreamingUser

abstract class ContentOwner<<Django Model>>{
    + get_statistics(obj): ...
}
ContentOwner "1..* \n owned_songs"<--->"0..* \n owners" BaseSong
ContentOwner "1..* \n owned_song_collections"<--->"0..* \n owners" SongCollection

class Artist<<DjangoModel>>{
    + bio: str
'    + hub: InfoHub
'    + artist_relations: ArtistRelation
}
StreamingUser <|- Artist
ContentOwner <|- Artist
'class ArtistRelation{
'    + related_to: Artist
'    + degree: int
'}

abstract class Hidable{
    + is_hidden: bool

    + {abstract} hide(): bool
    + {abstract} unhide(): bool
}
abstract class Bannable{
    + is_banned: bool

    + {abstract} ban(): bool
    + {abstract} unban(): bool
}

' ### Songs
class BaseSong<<DjangoModel>> extends Hidable, Bannable {
    + title: str
    + description: str
    + image: str | None
    + metadata: dict
    + duration: int
    + like_count: int
    + dislike_count: int

    + mpd_path: str
    + m3u8_path: str
}
BaseSong "0..* \n hashtags"<--->"0..* \n basesong_set" HashTag

class AuthorSong<<DjangoModel>>{
    + added_by_count(): int
    + get_stream_count(from: datetime, to: datetime, unique_only: bool): int
}
BaseSong <|- AuthorSong

' ### Song containers
class SongCollection<<DjangoModel>> implements Hidable, Bannable{
    + title: str
    + image: str | None
    + metadata: dict
}
SongCollection "1..* \n songs" <---> "0..* \n songcollection_set" BaseSong
SongCollection "0..* \n hashtags"<--->"0..* \n songcollections_set" HashTag

class AuthorSongCollection<<DjangoModel>> extends SongCollection{
    + added_by_count(): int
    + get_save_count(from: datetime, to: datetime, unique_only: bool): int
}
SongCollection <|- AuthorSongCollection

class Stream<<DjangoModel>>

Stream <|-left SongStream
Stream <|- SongCollectionStream

' ### Categorisation
class HashTag<<DjangoModel>>{
    type: str
    name: str
}
class Genre<<DjangoModel>>
HashTag <|- Genre
class Mood<<DjangoModel>>
HashTag <|- Mood
class Characteristic<<DjangoModel>>
HashTag <|- Characteristic

' layout
@enduml
