services:
  database:
    image: postgres:17
    ports:
      - '5432:5432'
    env_file:
      - ./src/backend/musikk/.env

#
#  rabbitmq:
#    container_name: rabbitmq
#    image: rabbitmq:latest
#    ports:
#      - '5672:5672'
#      - '15672:15672'
#
#  redis:
#    container_name: redis
#    image: redis:latest
#    ports:
#      - '6379:6379'

#  web:
#    container_name: web
#    build:
#      context: .
#      dockerfile: ./compose/local/django/Dockerfile
#      ssh:
#        - default
#    command: /start
#    volumes:
#      - ./src/backend:/app
#    ports:
#      - '8010:8000'
#    env_file:
#      - src/backend/.env
#    depends_on:
#      - redis
#      - db
#      - mongo
#
#  celery_worker:
#    container_name: celery-worker
#    build:
#      context: .
#      dockerfile: ./compose/local/django/Dockerfile
#    command: /start-celeryworker
#    volumes:
#      - ./src/backend:/app
#    env_file:
#      - src/backend/.env
#    depends_on:
#      - redis
#      - db
#
#  celery_beat:
#    container_name: celery-beat
#    build:
#      context: .
#      dockerfile: ./compose/local/django/Dockerfile
#    command: /start-celerybeat
#    volumes:
#      - ./src/backend:/app
#    env_file:
#      - src/backend/.env
#    depends_on:
#      - redis
#      - db

volumes:
  postgres_data:

