services:
  database:
    image: postgres:17
    ports:
      - '5432:5432'
    env_file:
      - ./src/backend/musikk/.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

