name: musikk-deploy

services:
  server:
    image: ddrddrr2/musikk-server:latest
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: musikk.settings.prod
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - ${DJANGO_PORT}
    volumes:
      - django_static:/app/staticfiles
      - django_media:/app/media
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:${DJANGO_PORT}/health/"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    networks:
      - main

  database:
    image: postgres:17
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - main

  celery_worker:
    image: ddrddrr2/musikk-server:latest
    entrypoint: ["./start-celery-worker.sh"]
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: musikk.settings.prod
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - django_media:/app/media
    networks:
      - main

  redis:
    image: redis:8.0-alpine
    command: [ "redis-server","--requirepass","${REDIS_PASSWORD}" ]
    expose:
      - 6379
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - main

  proxy:
    image: ddrddrr2/musikk-caddy:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - django_static:/app/staticfiles
      - django_media:/app/media
    networks:
      - main

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  django_static:
  django_media:

networks:
  main:
