name: musikk

services:
  server:
    image: ddrddrr2/musikk-server:latest
    depends_on:
      - database
    ports:
      - "8000:8000"
    volumes:
      - django_static:/app/staticfiles
      - django_media:/app/media
    env_file:
      - .env

  database:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  caddy:
    image: ddrddrr2/musikk-caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - django_static:/app/staticfiles
      - django_media:/app/media


volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  django_static:
  django_media: