services:
  database:
    image: postgres:17
    ports:
      - "5435:5432"
    env_file:
      - src/backend/musikk/.env
    volumes:
      - postgres_data2:/var/lib/postgresql/data


volumes:
  postgres_data2:

