name: musikk-deploy

services:
  server:
    image: ddrddrr2/musikk-server:latest
    depends_on:
      - database
    volumes:
      - django_static:/app/staticfiles
      - django_media:/app/media
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - main

  database:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - main

  proxy:
    image: ddrddrr2/musikk-caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - django_static:/app/staticfiles
      - django_media:/app/media
    networks:
      - main

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  django_static:
  django_media:

networks:
  main: