name: musikk-dev

services:
  server:
    build:
      context: ./src/backend/
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    depends_on:
      - database
      - redis
    expose:
      - ${DJANGO_PORT}
    volumes:
      - django_static:/app/staticfiles
      - django_media:/app/media
    networks:
      - main

  database:
    image: postgres:17
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main

  celery_worker:
    build:
      context: ./src/backend/
      dockerfile: docker/Dockerfile
    command: docker/start-celery-worker.sh
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      broker:
        condition: service_healthy
      database:
        condition: service_healthy
    volumes:
      - django_media:/app/media
    networks:
      - main

  broker:
    image: rabbitmq:4.1.1
    expose:
      - 5672
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - main

  redis:
    image: redis:8.0-alpine
    command: [ "redis-server","--requirepass","${REDIS_PASSWORD}" ]
    expose:
      - 6379
    env_file:
      - .env
    networks:
      - main

  proxy:
    build:
      context: ./src/frontend
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/frontend/docker/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - django_static:/app/staticfiles
      - django_media:/app/media
    networks:
      - main

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  django_static:
  django_media:
  rabbitmq_data:

networks:
  main: