# Generated by Django 5.1.7 on 2025-04-25 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("social", "0002_alter_comment_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplyNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "orig_comment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="social.comment",
                    ),
                ),
                (
                    "reply_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="social.comment",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_added"],
            },
        ),
    ]
