# Generated by Django 5.2.10 on 2026-05-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessagenotification",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="social.chat",
            ),
        ),
        migrations.AddField(
            model_name="chatmessagenotification",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="social.publication",
            ),
        ),
    ]
