# Generated by Django 5.1.7 on 2025-05-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_friendrequestnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequestnotification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
