# Generated by Django 5.1.7 on 2025-05-04 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_friendrequestnotification_is_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="friendrequestnotification",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="friendrequestnotification",
            name="date_modified",
        ),
        migrations.RemoveField(
            model_name="friendrequestnotification",
            name="id",
        ),
        migrations.RemoveField(
            model_name="friendrequestnotification",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="friendrequestnotification",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="replynotification",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="replynotification",
            name="date_modified",
        ),
        migrations.RemoveField(
            model_name="replynotification",
            name="id",
        ),
        migrations.RemoveField(
            model_name="replynotification",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="replynotification",
            name="uuid",
        ),
        migrations.AddField(
            model_name="friendrequestnotification",
            name="notification_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="notifications.notification",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="replynotification",
            name="notification_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="notifications.notification",
            ),
            preserve_default=False,
        ),
    ]
