# Generated by Django 5.1.7 on 2025-05-11 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notification_and_more"),
        ("social", "0003_remove_comment_content_type_remove_comment_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replynotification",
            name="orig_comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="social.publication",
            ),
        ),
        migrations.AlterField(
            model_name="replynotification",
            name="reply_comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="social.publication",
            ),
        ),
    ]
