# Generated by Django 5.1.7 on 2025-04-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="hashtag",
            name="recommendat_content_98a058_idx",
        ),
    ]
