# Generated by Django 5.1.7 on 2025-04-24 20:47

from django.db import migrations


def enable_pg_trgm(apps, schema_editor):
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0002_remove_hashtag_recommendat_content_98a058_idx"),
    ]

    operations = [
        migrations.RunPython(enable_pg_trgm),
    ]
