# Generated by Django 5.1.7 on 2025-05-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0003_auto_20250424_2047"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HashTag",
        ),
    ]
