# Generated by Django 5.2.10 on 2026-05-08 09:31

import uuid

import django.db.models.deletion
import utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=utils.paths.deafult_image_path
                    ),
                ),
                (
                    "is_direct",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates, whether the Chat is between two people only.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(max_length=2000)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_for_id", models.UUIDField()),
                ("attachment_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "publications",
                "ordering": ("date_added",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatMember",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="social.chat"
                    ),
                ),
            ],
        ),
    ]
