# Generated by Django 5.2.3 on 2025-12-06 11:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_for_id", models.PositiveIntegerField()),
                ("attachment_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "attachment_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attached_to",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "publications",
                "ordering": ("date_added",),
                "abstract": False,
            },
        ),
    ]
