# Generated by Django 5.1.7 on 2025-05-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_replynotification_orig_comment_and_more"),
        ("social", "0003_remove_comment_content_type_remove_comment_parent_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
