# Generated by Django 5.2.10 on 2026-03-15 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_chat_alter_publication_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='chat',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
    ]
