# Generated by Django 5.2.10 on 2026-04-26 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0004_alter_chat_title_alter_chat_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmember",
            name="last_read_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="social.publication",
            ),
        ),
    ]
