# Generated by Django 5.1.7 on 2025-03-31 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0006_songqueue_song_count"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streaminguser",
            name="song_queue",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user",
                to="streaming.songqueue",
            ),
        ),
    ]
