# Generated by Django 5.2.3 on 2025-12-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streaming", "0004_alter_basesong_authors_alter_songcredit_author"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="role",
            field=models.CharField(
                choices=[("base", "Base"), ("artist", "Artist")],
                db_index=True,
                default="base",
                max_length=16,
            ),
        ),
        migrations.DeleteModel(
            name="Artist",
        ),
    ]
