# Generated by Django 5.1.7 on 2025-04-26 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0003_likedsongs"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streaminguser",
            name="liked_songs",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liked_by",
                to="streaming.likedsongs",
            ),
        ),
    ]
