# Generated by Django 5.2.3 on 2025-06-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
