# Generated by Django 5.1.7 on 2025-04-12 20:27

import musikk.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_streaminguser_song_queue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="avatar",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to=musikk.utils.image_path
            ),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="display_name",
            field=models.CharField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
