# Generated by Django 5.2.10 on 2026-03-15 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser_role_delete_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='bio',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
    ]
