# Generated by Django 5.1.7 on 2025-04-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_streaminguser_liked_songs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="streaminguser",
            name="created_playlists",
        ),
    ]
