# Generated by Django 5.2.3 on 2025-11-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_baseuser_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baseuser",
            old_name="is_admin",
            new_name="is_staff",
        ),
    ]
