# Generated by Django 5.1.7 on 2025-04-18 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0010_userhistory_remove_songstream_song_and_more"),
        ("users", "0003_alter_baseuser_avatar_alter_baseuser_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="streaminguser",
            name="history",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user",
                to="streaming.userhistory",
            ),
        ),
    ]
