# Generated by Django 5.1.7 on 2025-05-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_streaminguser_created_playlists"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="bio",
        ),
        migrations.AddField(
            model_name="streaminguser",
            name="bio",
            field=models.TextField(default="", max_length=2000),
        ),
    ]
