# Generated by Django 5.1.7 on 2025-05-01 15:03

import users.user_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_artist_bio_streaminguser_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="baseuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="streaminguser",
            name="bio",
        ),
        migrations.AddField(
            model_name="baseuser",
            name="bio",
            field=models.TextField(default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="display_name",
            field=models.CharField(
                default=users.user_base.get_display_name, max_length=50
            ),
        ),
    ]
