# Generated by Django 5.1.7 on 2025-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_baseuser_first_name_remove_baseuser_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="streaminguser",
            name="friends",
            field=models.ManyToManyField(to="users.streaminguser"),
        ),
    ]
