# Generated by Django 5.1.7 on 2025-05-05 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0008_playbackstate_playbackdevice"),
        ("users", "0006_streaminguser_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="streaminguser",
            name="playback_state",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="streaming.playbackstate",
            ),
        ),
        migrations.AlterField(
            model_name="streaminguser",
            name="history",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user",
                to="streaming.userhistory",
            ),
        ),
        migrations.AlterField(
            model_name="streaminguser",
            name="liked_songs",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liked_by",
                to="streaming.likedsongs",
            ),
        ),
        migrations.AlterField(
            model_name="streaminguser",
            name="song_queue",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user",
                to="streaming.songqueue",
            ),
        ),
    ]
