# Generated by Django 5.1.7 on 2025-05-05 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0008_playbackstate_playbackdevice"),
        ("users", "0007_streaminguser_playback_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streaminguser",
            name="playback_state",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="streaming.playbackstate",
            ),
        ),
    ]
