# Generated by Django 5.1.7 on 2025-05-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0009_basesong_authors_songcollection_authors"),
        ("users", "0008_alter_streaminguser_playback_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streaminguser",
            name="liked_songs",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user",
                to="streaming.likedsongs",
            ),
        ),
    ]
