# Generated by Django 5.1.7 on 2025-05-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_streaminguser_liked_songs"),
    ]

    operations = [
        migrations.AddField(
            model_name="streaminguser",
            name="followed",
            field=models.ManyToManyField(related_name="followers", to="users.artist"),
        ),
    ]
