# Generated by Django 5.1.7 on 2025-05-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_streaminguser_followed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="owned_song_collections",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="owned_songs",
        ),
        migrations.DeleteModel(
            name="Label",
        ),
    ]
