@startuml DjangoServer

skinparam packageStyle rectangle

package "Reverse Proxy" as caddy

package "Django" as django {
    [SQL Database] as db
    [Event Channels] as eventstream
    [Serializers] as serializers
}

package "Audio Processor" as audioproc {
    [ffmpeg]
}

entity "Media Storage" as store

caddy --> django: API Call (REST/Multipart)
django --> db: Alter/Get Data
django --> eventstream: Create Event

django --> serializers: Serialize Data
serializers -up-> caddy: JSON Response

caddy --> django: Open SSE Stream
eventstream -up-> caddy: Send Event

django --> ffmpeg: Process Uploaded Audio
ffmpeg --> store: Upload Transcoded Audio
django <-- store: Retrieve for Streaming/Presentation

@enduml