@startuml FrontendSystem

!include ../_style.puml

actor "User" as user

package "Reverse Proxy/Static Files" as proxy

package "Single-Page Application" as spa {
    [UI] as ui
    [API Client] as api_client
    [WebSocket Client] as ws_client
    [Audio Player] as player
}

user ---> ui : interact
ui ----> user : render

ui ..> api_client : queries / mutations
ui ..> ws_client : subscribe / send
ui ..> player : drives playback

api_client <---> proxy : API requests / JSON responses
ws_client <---> proxy : WebSocket connection / events
player <---> proxy : streaming manifest / audio bytes


@enduml
