@startuml HighLevelSystem

actor User as user

skinparam packageStyle rectangle

package frontend
package proxy
package backend

user ---> proxy: Initial Page Load
proxy ---> user: Static Files (HTML/CSS/JS)

user ---> frontend: Interacts via UI
frontend ---> proxy: API / SSE / Audio Requests
proxy ---> backend: Forward API / SSE
backend ---> proxy: JSON / Events
proxy ---> frontend: Data / Events / Audio

@enduml