# Generated by Django 5.2.3 on 2025-06-23 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("streaming", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectioncredit",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collection_credits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collectioncredit",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_credits",
                to="streaming.collection",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="authors",
            field=models.ManyToManyField(
                through="streaming.CollectionCredit", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="collectionsong",
            name="collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collectionsongs",
                to="streaming.collection",
            ),
        ),
        migrations.AddField(
            model_name="collectionsong",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collectionsongs",
                to="streaming.basesong",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="base_songs",
            field=models.ManyToManyField(
                through="streaming.CollectionSong", to="streaming.basesong"
            ),
        ),
        migrations.AddField(
            model_name="playbackdevice",
            name="playback_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="streaming.playbackstate",
            ),
        ),
        migrations.AddField(
            model_name="songcredit",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="song_credits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="songcredit",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credits",
                to="streaming.basesong",
            ),
        ),
        migrations.AddField(
            model_name="basesong",
            name="authors",
            field=models.ManyToManyField(
                through="streaming.SongCredit", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="songqueuenode",
            name="next",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="streaming.songqueuenode",
            ),
        ),
        migrations.AddField(
            model_name="songqueuenode",
            name="prev",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="streaming.songqueuenode",
            ),
        ),
        migrations.AddField(
            model_name="songqueuenode",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="streaming.collectionsong",
            ),
        ),
        migrations.AddField(
            model_name="songqueuenode",
            name="song_queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="streaming.songqueue",
            ),
        ),
        migrations.AddField(
            model_name="songqueue",
            name="add_after",
            field=models.OneToOneField(
                default=None,
                help_text="The node after which the songs will be appended when `Add To Queue` is used. If the song/collection is appended, equal to this song/last song in collection.Otherwise is equal to `head`.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="streaming.songqueuenode",
            ),
        ),
        migrations.AddField(
            model_name="songqueue",
            name="head",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="streaming.songqueuenode",
            ),
        ),
        migrations.AddField(
            model_name="songqueue",
            name="tail",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="streaming.songqueuenode",
            ),
        ),
    ]
