# Generated by Django 5.1.7 on 2025-03-29 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("streaming", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="songcollectionstream",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.streaminguser",
            ),
        ),
        migrations.AddField(
            model_name="basesong",
            name="metadata",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="song",
                to="streaming.songmetadata",
            ),
        ),
        migrations.AddField(
            model_name="songqueuenode",
            name="next",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="streaming.songqueuenode",
            ),
        ),
        migrations.AddField(
            model_name="songqueuenode",
            name="prev",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="streaming.songqueuenode",
            ),
        ),
        migrations.AddField(
            model_name="songqueuenode",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="streaming.basesong"
            ),
        ),
        migrations.AddField(
            model_name="songqueuenode",
            name="song_queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="streaming.songqueue"
            ),
        ),
        migrations.AddField(
            model_name="songqueue",
            name="head",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="streaming.songqueuenode",
            ),
        ),
        migrations.AddField(
            model_name="songqueue",
            name="tail",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="streaming.songqueuenode",
            ),
        ),
        migrations.AddField(
            model_name="songstream",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streams",
                to="streaming.basesong",
            ),
        ),
        migrations.AddField(
            model_name="songstream",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.streaminguser",
            ),
        ),
    ]
