# Generated by Django 5.2.10 on 2026-05-08 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("streaming", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectioncredit",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collection_credits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collectioncredit",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_credits",
                to="streaming.collection",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="authors",
            field=models.ManyToManyField(
                related_name="collections",
                through="streaming.CollectionCredit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collectionsong",
            name="collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collectionsongs",
                to="streaming.collection",
            ),
        ),
        migrations.AddField(
            model_name="collectionsong",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collectionsongs",
                to="streaming.basesong",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="base_songs",
            field=models.ManyToManyField(
                through="streaming.CollectionSong", to="streaming.basesong"
            ),
        ),
        migrations.AddField(
            model_name="playbackcontext",
            name="collection",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="streaming.collection",
            ),
        ),
        migrations.AddField(
            model_name="playerstate",
            name="context",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="streaming.playbackcontext",
            ),
        ),
        migrations.AddField(
            model_name="playerstate",
            name="current_collection_song",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="streaming.collectionsong",
            ),
        ),
        migrations.AddField(
            model_name="queueitem",
            name="collection_song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="streaming.collectionsong",
            ),
        ),
        migrations.AddField(
            model_name="queuesource",
            name="collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="streaming.collection",
            ),
        ),
        migrations.AddField(
            model_name="queuesource",
            name="collection_song",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="streaming.collectionsong",
            ),
        ),
        migrations.AddField(
            model_name="songcredit",
            name="author",
            field=models.ForeignKey(
                limit_choices_to={"role": "artist"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_songs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="songcredit",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credits",
                to="streaming.basesong",
            ),
        ),
        migrations.AddField(
            model_name="basesong",
            name="authors",
            field=models.ManyToManyField(
                limit_choices_to={"role": "artist"},
                related_name="authored_songs",
                through="streaming.SongCredit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="queuesource",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="streaming.songqueue",
            ),
        ),
        migrations.AddField(
            model_name="queueitem",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="streaming.songqueue",
            ),
        ),
        migrations.AddField(
            model_name="playerstate",
            name="queue",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="streaming.songqueue"
            ),
        ),
        migrations.AddField(
            model_name="streamingprofile",
            name="liked_collections",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="streaming.collection"
            ),
        ),
        migrations.AddField(
            model_name="streamingprofile",
            name="player",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="streaming.playerstate"
            ),
        ),
        migrations.AddField(
            model_name="streamingprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="queueitem",
            index=models.Index(
                fields=["queue", "position"], name="streaming_q_queue_i_bee6aa_idx"
            ),
        ),
    ]
