# Generated by Django 5.1.7 on 2025-03-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basesong",
            name="mpd",
            field=models.FilePathField(
                blank=True,
                default="",
                max_length=1024,
                path="/Users/mazda/studies/content/audio_content",
            ),
        ),
    ]
