# Generated by Django 5.1.7 on 2025-04-26 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikedSongs",
            fields=[
                (
                    "songcollection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="streaming.songcollection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("streaming.songcollection",),
        ),
    ]
