# Generated by Django 5.2.3 on 2025-06-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songcredit",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="song_credits",
                to="streaming.basesong",
            ),
        ),
    ]
