# Generated by Django 5.2.3 on 2025-12-10 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streaming", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="streamingprofile",
            name="playback_state",
        ),
        migrations.DeleteModel(
            name="PlaybackDevice",
        ),
        migrations.DeleteModel(
            name="PlaybackState",
        ),
    ]
