# Generated by Django 5.1.7 on 2025-04-27 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0003_likedsongs"),
        ("users", "0003_remove_streaminguser_created_playlists"),
    ]

    operations = [
        migrations.AddField(
            model_name="basesong",
            name="authors",
            field=models.ManyToManyField(to="users.artist"),
        ),
        migrations.AddField(
            model_name="songcollection",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SongAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "author_priority",
                    models.IntegerField(
                        default=0,
                        help_text="Priority in which the author will be displayed.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.artist",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streaming.basesong",
                    ),
                ),
            ],
            options={
                "ordering": ("author_priority",),
            },
        ),
        migrations.CreateModel(
            name="SongCollectionCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "creator_priority",
                    models.IntegerField(
                        default=0,
                        help_text="Priority in which the creators will be displayed.",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.streaminguser",
                    ),
                ),
                (
                    "song_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streaming.songcollection",
                    ),
                ),
            ],
            options={
                "ordering": ("creator_priority",),
            },
        ),
    ]
