# Generated by Django 5.1.7 on 2025-03-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0003_alter_basesong_mpd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basesong",
            name="mpd",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Path to the mpd file representing the song.",
                max_length=1024,
            ),
        ),
    ]
