# Generated by Django 5.2.3 on 2025-12-14 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streaming", "0003_remove_streamingprofile_playback_state_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="basesong",
            name="authors",
            field=models.ManyToManyField(
                limit_choices_to={"role": "artist"},
                related_name="authored_songs",
                through="streaming.SongCredit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="songcredit",
            name="author",
            field=models.ForeignKey(
                limit_choices_to={"role": "artist"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_songs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
