# Generated by Django 5.1.7 on 2025-04-27 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "streaming",
            "0004_basesong_authors_songcollection_private_songauthor_and_more",
        ),
        ("users", "0003_remove_streaminguser_created_playlists"),
    ]

    operations = [
        migrations.CreateModel(
            name="SongCollectionAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "author_priority",
                    models.IntegerField(
                        default=0,
                        help_text="Priority in which the authors will be displayed.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.streaminguser",
                    ),
                ),
                (
                    "song_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streaming.songcollection",
                    ),
                ),
            ],
            options={
                "ordering": ("author_priority",),
            },
        ),
        migrations.DeleteModel(
            name="SongCollectionCreator",
        ),
    ]
