# Generated by Django 5.2.10 on 2026-03-15 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_alter_basesong_authors_alter_songcredit_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesong',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collectioncredit',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collectionsong',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='songcredit',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='songqueue',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='songqueuenode',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='streamingprofile',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
    ]
