# Generated by Django 5.1.7 on 2025-03-31 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0004_alter_basesong_mpd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basesong",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="songcollection",
            name="songs",
        ),
        migrations.AddField(
            model_name="songcollection",
            name="songs",
            field=models.ManyToManyField(
                through="streaming.SongCollectionSong", to="streaming.basesong"
            ),
        ),
        migrations.AlterField(
            model_name="songcollectionsong",
            name="position",
            field=models.IntegerField(
                default=None,
                help_text="The order of the song in the collection.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="songcollectionsong",
            name="song_collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="streaming.songcollection",
            ),
        ),
    ]
