# Generated by Django 5.2.10 on 2026-03-29 11:18

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_alter_basesong_uuid_alter_collection_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songqueue',
            name='head',
        ),
        migrations.RemoveField(
            model_name='songqueue',
            name='add_after',
        ),
        migrations.RemoveField(
            model_name='songqueue',
            name='tail',
        ),
        migrations.RemoveField(
            model_name='songqueue',
            name='song_count',
        ),
        migrations.AddField(
            model_name='songqueue',
            name='context_collection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='streaming.collection'),
        ),
        migrations.AddField(
            model_name='songqueue',
            name='context_offset',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='songqueue',
            name='context_skip_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='songqueue',
            name='current_song',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='streaming.collectionsong'),
        ),
        migrations.AddField(
            model_name='songqueue',
            name='history_cursor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='songqueue',
            name='next_item_position',
            field=models.DecimalField(decimal_places=12, default=Decimal('1000'), max_digits=24),
        ),
        migrations.CreateModel(
            name='QueueSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('song', 'Song'), ('collection', 'Collection')], max_length=16)),
                ('collection_offset', models.IntegerField(default=-1)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='streaming.collection')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='streaming.songqueue')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='streaming.collectionsong')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('position', models.DecimalField(decimal_places=12, max_digits=24)),
                ('from_context', models.BooleanField(default=False)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='streaming.songqueue')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='streaming.collectionsong')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='streaming.queuesource')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.DeleteModel(
            name='SongQueueNode',
        ),
        migrations.AddIndex(
            model_name='queueitem',
            index=models.Index(fields=['queue', 'position'], name='streaming_q_queue_i_bee6aa_idx'),
        ),
    ]
