# Generated by Django 5.1.7 on 2025-03-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "streaming",
            "0005_remove_basesong_duration_alter_songcollection_songs_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="songqueue",
            name="song_count",
            field=models.IntegerField(default=0),
        ),
    ]
