# Generated by Django 5.1.7 on 2025-04-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0005_songcollectionauthor_delete_songcollectioncreator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basesong",
            name="authors",
        ),
    ]
