# Generated by Django 5.2.10 on 2026-03-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streaming", "0006_remove_songqueue_head_remove_songqueue_add_after_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="queueitem",
            old_name="song",
            new_name="collection_song",
        ),
        migrations.RenameField(
            model_name="queuesource",
            old_name="collection_offset",
            new_name="collection_cursor",
        ),
        migrations.RenameField(
            model_name="queuesource",
            old_name="song",
            new_name="collection_song",
        ),
        migrations.RenameField(
            model_name="songqueue",
            old_name="context_offset",
            new_name="context_cursor",
        ),
        migrations.RenameField(
            model_name="songqueue",
            old_name="current_song",
            new_name="current_collection_song",
        ),
        migrations.RemoveField(
            model_name="queueitem",
            name="from_context",
        ),
        migrations.RemoveField(
            model_name="queueitem",
            name="source",
        ),
        migrations.AddField(
            model_name="queueitem",
            name="origin",
            field=models.CharField(
                choices=[
                    ("context", "Context"),
                    ("source", "Source"),
                    ("user", "User"),
                ],
                default="source",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="queueitem",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="streaming.songqueue",
            ),
        ),
        migrations.AlterField(
            model_name="queuesource",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="streaming.songqueue",
            ),
        ),
    ]
