# Generated by Django 5.1.7 on 2025-04-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0006_remove_basesong_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="basesong",
            name="draft",
            field=models.BooleanField(default=False),
        ),
    ]
