# Generated by Django 5.1.7 on 2025-04-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0006_songqueue_song_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="basesong",
            name="content_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Path to the directory with all song files.",
                max_length=1024,
            ),
        ),
    ]
