# Generated by Django 5.1.7 on 2025-04-13 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0007_basesong_content_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="songqueue",
            name="add_after",
            field=models.OneToOneField(
                default=None,
                help_text="The node after which the songs will be appended when `Add To Queue` is used. If the song/collection is appended, equal to this song/last song in collection.Otherwise is equal to `head`.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="streaming.songqueuenode",
            ),
        ),
    ]
