# Generated by Django 5.1.7 on 2025-04-14 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0008_songqueue_add_after"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songqueuenode",
            name="song_queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="streaming.songqueue",
            ),
        ),
    ]
