# Generated by Django 5.1.7 on 2025-05-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0008_playbackstate_playbackdevice"),
        ("users", "0008_alter_streaminguser_playback_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="basesong",
            name="authors",
            field=models.ManyToManyField(
                through="streaming.SongAuthor", to="users.artist"
            ),
        ),
        migrations.AddField(
            model_name="songcollection",
            name="authors",
            field=models.ManyToManyField(
                through="streaming.SongCollectionAuthor", to="users.streaminguser"
            ),
        ),
    ]
