# Generated by Django 5.1.7 on 2025-05-06 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0009_basesong_authors_songcollection_authors"),
        ("users", "0009_alter_streaminguser_liked_songs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songauthor",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_song_links",
                to="users.artist",
            ),
        ),
        migrations.AlterField(
            model_name="songauthor",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_links",
                to="streaming.basesong",
            ),
        ),
        migrations.AlterField(
            model_name="songcollectionauthor",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_collections_link",
                to="users.streaminguser",
            ),
        ),
        migrations.AlterField(
            model_name="songcollectionauthor",
            name="song_collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_links",
                to="streaming.songcollection",
            ),
        ),
        migrations.AlterField(
            model_name="songcollectionsong",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_links",
                to="streaming.basesong",
            ),
        ),
        migrations.AlterField(
            model_name="songcollectionsong",
            name="song_collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs_links",
                to="streaming.songcollection",
            ),
        ),
    ]
