# Generated by Django 5.1.7 on 2025-04-18 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("streaming", "0009_alter_songqueuenode_song_queue"),
        ("users", "0003_alter_baseuser_avatar_alter_baseuser_display_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserHistory",
            fields=[
                (
                    "songcollection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="streaming.songcollection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("streaming.songcollection",),
        ),
        migrations.RemoveField(
            model_name="songstream",
            name="song",
        ),
        migrations.RemoveField(
            model_name="songstream",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="songcollectionsong",
            options={"ordering": ("position",)},
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.streaminguser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="SongCollectionStream",
        ),
        migrations.DeleteModel(
            name="SongStream",
        ),
    ]
