# Generated by Django 5.1.7 on 2025-05-07 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0010_alter_songauthor_author_alter_songauthor_song_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playbackstate",
            name="playing_collection",
        ),
        migrations.RemoveField(
            model_name="playbackstate",
            name="playing_song",
        ),
        migrations.AlterField(
            model_name="songqueuenode",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="streaming.songcollectionsong",
            ),
        ),
    ]
