# Generated by Django 5.2.10 on 2026-04-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0011_remove_queueitem_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesong',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
