# Generated by Django 5.1.7 on 2025-05-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0011_remove_playbackstate_playing_collection_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="songcollection_ptr",
        ),
        migrations.AddField(
            model_name="songcollection",
            name="type",
            field=models.CharField(
                choices=[("playlist", "Playlist"), ("album", "Album")],
                default="playlist",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="Playlist",
        ),
    ]
