# Generated by Django 5.2.10 on 2026-04-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0012_add_duration_ms_to_basesong'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesong',
            name='loudness_lufs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basesong',
            name='source_bitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basesong',
            name='source_codec',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='basesong',
            name='true_peak_dbtp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
