# Generated by Django 5.1.7 on 2025-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0012_remove_playlist_songcollection_ptr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbackdevice",
            name="name",
            field=models.CharField(default="aboba", max_length=255),
            preserve_default=False,
        ),
    ]
