# Generated by Django 5.1.7 on 2025-05-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0013_playbackdevice_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="songcollection",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="basesong",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="stream",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="stream",
            name="user",
        ),
        migrations.RemoveField(
            model_name="basesong",
            name="dislike_count",
        ),
        migrations.RemoveField(
            model_name="basesong",
            name="like_count",
        ),
        migrations.DeleteModel(
            name="SongCollectionMetadata",
        ),
        migrations.DeleteModel(
            name="SongMetadata",
        ),
        migrations.DeleteModel(
            name="Stream",
        ),
    ]
