# Generated by Django 5.2.10 on 2026-04-26 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streaming", "0013_add_loudness_and_source_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstate",
            name="context",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="streaming.playbackcontext",
            ),
        ),
        migrations.AlterField(
            model_name="playerstate",
            name="queue",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="streaming.songqueue"
            ),
        ),
        migrations.AlterField(
            model_name="streamingprofile",
            name="player",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="streaming.playerstate"
            ),
        ),
    ]
