# Generated by Django 5.1.7 on 2025-05-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0014_remove_songcollection_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basesong",
            name="m3u8",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Path to the m3u8 file representing the song.",
                max_length=1024,
            ),
        ),
    ]
