# Generated by Django 5.2.3 on 2025-06-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0015_basesong_m3u8"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="likedsongs",
            options={"ordering": ("-date_added",)},
        ),
        migrations.AlterModelOptions(
            name="userhistory",
            options={"ordering": ("-date_added",)},
        ),
    ]
